syntax = "proto3";

package blog.v1;

enum UserRole {
  USER_ROLE_UNSPECIFIED = 0;
  USER_ROLE_USER = 1;
  USER_ROLE_ADMIN = 2;
}

message User {
  int64 id = 1;
  string email = 2;
  UserRole role = 3;
  optional double created_at = 4;
  optional double updated_at = 5;
}

message GetUserRequest {
  int64 user_id = 1;
}

message CreateUserRequest {
  string email = 1;
  UserRole role = 2;
}

message UpdateUserRoleRequest {
  int64 user_id = 1;
  UserRole role = 2;
}

service UsersService {
  rpc CreateUser(CreateUserRequest) returns (User);
  rpc GetUser(GetUserRequest) returns (User);
  rpc UpdateUserRole(UpdateUserRoleRequest) returns (User);
}