# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07\x62log.v1\"E\n\x11UserCreateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\x86\x01\n\rTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x03\x12\x12\n\ntoken_type\x18\x04 \x01(\t\x12 \n\x18refresh_token_expires_in\x18\x05 \x01(\x03\x32\xc3\x01\n\x0b\x41uthService\x12@\n\nCreateUser\x12\x1a.blog.v1.UserCreateRequest\x1a\x16.blog.v1.TokenResponse\x12\x36\n\x05Login\x12\x15.blog.v1.LoginRequest\x1a\x16.blog.v1.TokenResponse\x12:\n\x07Refresh\x12\x17.blog.v1.RefreshRequest\x1a\x16.blog.v1.TokenResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERCREATEREQUEST._serialized_start=23
  _USERCREATEREQUEST._serialized_end=92
  _LOGINREQUEST._serialized_start=94
  _LOGINREQUEST._serialized_end=141
  _REFRESHREQUEST._serialized_start=143
  _REFRESHREQUEST._serialized_end=182
  _TOKENRESPONSE._serialized_start=185
  _TOKENRESPONSE._serialized_end=319
  _AUTHSERVICE._serialized_start=322
  _AUTHSERVICE._serialized_end=517
# @@protoc_insertion_point(module_scope)
