# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api_specs.python_lib import blog_pb2 as blog__pb2
from api_specs.python_lib import common_pb2 as common__pb2


class BlogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCategory = channel.unary_unary(
                '/blog.v1.BlogService/CreateCategory',
                request_serializer=blog__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=blog__pb2.Category.FromString,
                )
        self.GetCategory = channel.unary_unary(
                '/blog.v1.BlogService/GetCategory',
                request_serializer=blog__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=blog__pb2.Category.FromString,
                )
        self.GetCategories = channel.unary_unary(
                '/blog.v1.BlogService/GetCategories',
                request_serializer=blog__pb2.GetCategoriesRequest.SerializeToString,
                response_deserializer=blog__pb2.GetCategoriesResponse.FromString,
                )
        self.UpdateCategory = channel.unary_unary(
                '/blog.v1.BlogService/UpdateCategory',
                request_serializer=blog__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=blog__pb2.Category.FromString,
                )
        self.DeleteCategory = channel.unary_unary(
                '/blog.v1.BlogService/DeleteCategory',
                request_serializer=blog__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=common__pb2.BoolResponse.FromString,
                )
        self.CreatePost = channel.unary_unary(
                '/blog.v1.BlogService/CreatePost',
                request_serializer=blog__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=blog__pb2.Post.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/blog.v1.BlogService/GetPost',
                request_serializer=blog__pb2.GetPostRequest.SerializeToString,
                response_deserializer=blog__pb2.Post.FromString,
                )
        self.GetPosts = channel.unary_unary(
                '/blog.v1.BlogService/GetPosts',
                request_serializer=blog__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=blog__pb2.GetPostsResponse.FromString,
                )
        self.GetPostsByCategory = channel.unary_unary(
                '/blog.v1.BlogService/GetPostsByCategory',
                request_serializer=blog__pb2.GetPostsByCategoryRequest.SerializeToString,
                response_deserializer=blog__pb2.GetPostsResponse.FromString,
                )
        self.UpdatePost = channel.unary_unary(
                '/blog.v1.BlogService/UpdatePost',
                request_serializer=blog__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=blog__pb2.Post.FromString,
                )
        self.DeletePost = channel.unary_unary(
                '/blog.v1.BlogService/DeletePost',
                request_serializer=blog__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=common__pb2.BoolResponse.FromString,
                )


class BlogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostsByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=blog__pb2.CreateCategoryRequest.FromString,
                    response_serializer=blog__pb2.Category.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=blog__pb2.GetCategoryRequest.FromString,
                    response_serializer=blog__pb2.Category.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=blog__pb2.GetCategoriesRequest.FromString,
                    response_serializer=blog__pb2.GetCategoriesResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=blog__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=blog__pb2.Category.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=blog__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=common__pb2.BoolResponse.SerializeToString,
            ),
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=blog__pb2.CreatePostRequest.FromString,
                    response_serializer=blog__pb2.Post.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=blog__pb2.GetPostRequest.FromString,
                    response_serializer=blog__pb2.Post.SerializeToString,
            ),
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=blog__pb2.GetPostsRequest.FromString,
                    response_serializer=blog__pb2.GetPostsResponse.SerializeToString,
            ),
            'GetPostsByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostsByCategory,
                    request_deserializer=blog__pb2.GetPostsByCategoryRequest.FromString,
                    response_serializer=blog__pb2.GetPostsResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=blog__pb2.UpdatePostRequest.FromString,
                    response_serializer=blog__pb2.Post.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=blog__pb2.DeletePostRequest.FromString,
                    response_serializer=common__pb2.BoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blog.v1.BlogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/CreateCategory',
            blog__pb2.CreateCategoryRequest.SerializeToString,
            blog__pb2.Category.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/GetCategory',
            blog__pb2.GetCategoryRequest.SerializeToString,
            blog__pb2.Category.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/GetCategories',
            blog__pb2.GetCategoriesRequest.SerializeToString,
            blog__pb2.GetCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/UpdateCategory',
            blog__pb2.UpdateCategoryRequest.SerializeToString,
            blog__pb2.Category.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/DeleteCategory',
            blog__pb2.DeleteCategoryRequest.SerializeToString,
            common__pb2.BoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/CreatePost',
            blog__pb2.CreatePostRequest.SerializeToString,
            blog__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/GetPost',
            blog__pb2.GetPostRequest.SerializeToString,
            blog__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/GetPosts',
            blog__pb2.GetPostsRequest.SerializeToString,
            blog__pb2.GetPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPostsByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/GetPostsByCategory',
            blog__pb2.GetPostsByCategoryRequest.SerializeToString,
            blog__pb2.GetPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/UpdatePost',
            blog__pb2.UpdatePostRequest.SerializeToString,
            blog__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.v1.BlogService/DeletePost',
            blog__pb2.DeletePostRequest.SerializeToString,
            common__pb2.BoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
