# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x07\x62log.v1\"\x92\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x1f\n\x04role\x18\x03 \x01(\x0e\x32\x11.blog.v1.UserRole\x12\x17\n\ncreated_at\x18\x04 \x01(\x01H\x00\x88\x01\x01\x12\x17\n\nupdated_at\x18\x05 \x01(\x01H\x01\x88\x01\x01\x42\r\n\x0b_created_atB\r\n\x0b_updated_at\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"C\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x1f\n\x04role\x18\x02 \x01(\x0e\x32\x11.blog.v1.UserRole\"I\n\x15UpdateUserRoleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x1f\n\x04role\x18\x02 \x01(\x0e\x32\x11.blog.v1.UserRole*N\n\x08UserRole\x12\x19\n\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n\x0eUSER_ROLE_USER\x10\x01\x12\x13\n\x0fUSER_ROLE_ADMIN\x10\x02\x32\xbb\x01\n\x0cUsersService\x12\x37\n\nCreateUser\x12\x1a.blog.v1.CreateUserRequest\x1a\r.blog.v1.User\x12\x31\n\x07GetUser\x12\x17.blog.v1.GetUserRequest\x1a\r.blog.v1.User\x12?\n\x0eUpdateUserRole\x12\x1e.blog.v1.UpdateUserRoleRequest\x1a\r.blog.v1.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERROLE._serialized_start=352
  _USERROLE._serialized_end=430
  _USER._serialized_start=25
  _USER._serialized_end=171
  _GETUSERREQUEST._serialized_start=173
  _GETUSERREQUEST._serialized_end=206
  _CREATEUSERREQUEST._serialized_start=208
  _CREATEUSERREQUEST._serialized_end=275
  _UPDATEUSERROLEREQUEST._serialized_start=277
  _UPDATEUSERROLEREQUEST._serialized_end=350
  _USERSSERVICE._serialized_start=433
  _USERSSERVICE._serialized_end=620
# @@protoc_insertion_point(module_scope)
